### ISSUE TITLE
Unable to run the docker image

### ISSUE THREAD

**Issue by F0x06** [pbu88/diffy#93]
Hi ! i managed to build the Docker image after the PR of @markwbrown thanks ! (issue https://github.com/pbu88/diffy/issues/89)

now when running the docker container i have this error:

```bash
docker-compose build --no-cache
docker-compose up
```
```javascript
[+] Running 1/0
 ✔ Container diffy-web-1  Created                                                                                                                                       0.0s 
Attaching to web-1
web-1  | 
web-1  | > diffy@1.0.0 start
web-1  | > sh ./run.sh
web-1  | 
web-1  | node:internal/modules/cjs/loader:936
web-1  |   throw err;
web-1  |   ^
web-1  | 
web-1  | Error: Cannot find module 'diffy-models'
web-1  | Require stack:
web-1  | - /diffy/backend/dist/src/actions/GetSharedDiffAction.js
web-1  | - /diffy/backend/dist/src/App.js
web-1  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
web-1  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
web-1  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
web-1  |     at require (node:internal/modules/cjs/helpers:94:18)
web-1  |     at Object.<anonymous> (/diffy/backend/dist/src/actions/GetSharedDiffAction.js:4:24)
web-1  |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
web-1  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
web-1  |     at Module.load (node:internal/modules/cjs/loader:981:32)
web-1  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
web-1  |     at Module.require (node:internal/modules/cjs/loader:1005:19) {
web-1  |   code: 'MODULE_NOT_FOUND',
web-1  |   requireStack: [
web-1  |     '/diffy/backend/dist/src/actions/GetSharedDiffAction.js',
web-1  |     '/diffy/backend/dist/src/App.js'
web-1  |   ]
web-1  | }
```

Thanks.

**Comment by F0x06** [comment]
Removed all the images found with `docker image ls | grep diffy` apparently `--no-cache` was not enough. Now it works.

**Comment by F0x06** [comment]
In addition this is my docker-compose file with mongoDB, maybe you can include it also @pbu88 ?

```yml
version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: diffy
    ports:
      - 3000:3000
    volumes:
      - ./:/diffy
    environment:
      - NODE_ENV=production
      - DIFFY_WEB_HOST=0.0.0.0
      - DIFFY_GA_ANALYTICS_KEY=none
      - DIFFY_DB_HOST=mongo
    stop_signal: SIGINT

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: diffy
    volumes:
      - ./mongo_data:/data/db
```
